services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: >
      sh -c "npm run start"
    ports:
      - ${EXPRESS_SERVER_PORT}:${EXPRESS_SERVER_PORT}
    env_file:
      - ./.env.public
    depends_on:
      - db
  db:
    restart: always
    image: mongo:latest
    container_name: db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - ./.env.public
    volumes:
      - ./db_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--version" ]
      timeout: 15s
      interval: 5s
      retries: 3

volumes:
  db_data:
    driver: local
