# Node version
ARG NODE_VERSION=20.9.0

# ------------------------------------------------------BACKEND

FROM node:${NODE_VERSION} as BACKEND

LABEL maintainer="2023 MyHomeworks, { }"

WORKDIR /app/API

COPY ./package.json .

RUN npm install

COPY . .